//  Quotes
export const REQUEST_QUOTES_START = 'REQUEST_QUOTES_START'
export const REQUEST_QUOTES_ARRAY_START = 'REQUEST_QUOTES_ARRAY_START'
export const REQUEST_QUOTES_END = 'REQUEST_QUOTES_END'
export const RECEIVE_QUOTES_FULFILLED = 'RECEIVE_QUOTES_FULFILLED'
export const REQUEST_QUOTES_FAILED = 'REQUEST_USER_REPOS_FAILED'

export const MAKE_ORDER_START = 'MAKE_ORDER_START'
export const MAKE_ORDER_FULFILLED = 'MAKE_ORDER_FULFILLED'
export const MAKE_ORDER_FAILURE = 'MAKE_ORDER_FAILURE'

export const REQUEST_TERMS_START = 'REQUEST_TERMS_START'
export const REQUEST_TERMS_FULFILLED = 'REQUEST_TERMS_FULFILLED'
export const REQUEST_TERMS_FAILURE = 'REQUEST_TERMS_FAILURE'

export const VERIFICATE_PHONE_START = 'VERIFICATE_PHONE_START'
export const VERIFICATE_PHONE_FULFILLED = 'VERIFICATE_PHONE_FULFILLED'
export const VERIFICATE_PHONE_FAILURE = 'VERIFICATE_PHONE_FAILURE'

export const VERIFICATE_CODE_START = 'VERIFICATE_CODE_START'
export const VERIFICATE_CODE_FULFILLED = 'VERIFICATE_CODE_FULFILLED'
export const VERIFICATE_CODE_FAILURE = 'VERIFICATE_CODE_FAILURE'
export const VERIFICATE_CODE_ERROR = 'VERIFICATE_CODE_ERROR'
export const VERIFICATE_CODE_ERROR_REMOVE = 'VERIFICATE_CODE_ERROR_REMOVE'

export const SET_VISIBILITY = 'SET_VISIBILITY'

export const CHECKIN_USER_START = 'CHECKIN_USER_START'
export const CHECKIN_USER_FULFILLED = 'CHECKIN_USER_FULFILLED'
export const CHECKIN_USER_FAILED = 'CHECKIN_USER_FAILURE'

export const SEND_EVENT_START = 'SEND_EVENT_START'
export const SEND_EVENT_FULFILLED = 'SEND_EVENT_FULFILLED'
export const SEND_EVENT_FAILURE = 'SEND_EVENT_FAILURE'

export const GET_RANGE_START = 'GET_RANGE_START'
